dbt_test:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST') }}"
      port: "{{ env_var('TRINO_PORT') | as_number }}"
      user: "{{ env_var('TRINO_USER') }}"
      password: "{{ env_var('TRINO_PASSWORD') }}"
      catalog: "{{ env_var('TRINO_CATALOG') }}"
      schema: "{{ env_var('TRINO_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS') | as_number }}"
      http_scheme: "{{ env_var('TRINO_HTTP_SCHEME') }}"
